# see: https://cloud.google.com/appengine/docs/standard/python3/config/appref

# TODO: not work
# django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.2.0", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.

runtime: python37
entrypoint: bash -c "sh ./config/startup.sh && gunicorn --chdir ./app/ -b :$PORT wsgi"

service: default

instance_class: F1
automatic_scaling:
  target_throughput_utilization: 0.6
  min_instances: 1
  max_instances: 2

handlers:
- url: /static
  static_dir: static/

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto


beta_settings:
    cloud_sql_instances: geodjango-postgis-gae-001:asia-northeast1:app-main
